apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prod
    
  template:
      metadata:
        name: myweb
        labels:
          env: prod
          
      spec:
        containers:
        - name: myweb
          image: mayank1998/mayank-docker-images:v1
