apiVersion: v1
kind: Pod
metadata:
  name: mayank1
  labels:
    app: frontend
    team: team2
    region: IN
    env: prod
spec:
  containers:
    - name: mk
      image: mayank1998/mayank-docker-images:v4
