apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  selector:
    app: web
  template:
    metadata:
      name: mk
      labels:
        app: web
    spec:
      containers:
      - name: mk
        image: vimal13/apache-webserver-php