apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
    matchExpressions:
      - {key: team, operator: In, values: [ team1, team2 ]}
      - {key: tier, operator: In, values: [ frontend ]}

  template:
      metadata:
        name: myweb
        labels:
          env: prod
          team: team1
          tier: frontend
      spec:
        containers:
        - name: myweb
          image: mayank1998/mayank-docker-images:v4
