apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 4
  selector:
    app: web
  template:
    metadata:
      name: mk
      labels:
        app: web
    spec:
      containers:
      - name: mk
        image: mayank1998/mayank-docker-images:v4
